version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
  chatgpt-share-server:
    image: xyhelper/chatgpt-share-server:latest
    restart: always
    ports:
      - 8300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 内容审核及速率限制
      AUDIT_LIMIT_URL: "http://chatgpt-share-server-fox:6956/api/auditLimit"
      OAUTH_URL: "http://chatgpt-share-server-fox:6956/api/chatShareServer/oauth"
      APIAUTH: Doraemon
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
  ## grok-mirror
  grok-share-server:
    image: lyy0709/grok-share-server:dev
    restart: always
    ports:
      - 8301:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      #PROXY_URL: "http://proxy:8080/proxy" # 代理服务地址,支持http和https，socks5，没有则留空默认走本地
      CHATPROXY: "http://chatproxy:8080/proxy" # 网关配置，留空则不使用网关走本地代理
      # 内容审核及速率限制
      AUDIT_LIMIT_URL: "http://chatgpt-share-server-fox:6956/api/grok/auditLimit"
      OAUTH_URL: "http://chatgpt-share-server-fox:6956/api/grok/oauth"
      APIAUTH: Doraemon
    volumes:
      - ./grok_config.yaml:/app/config.yaml
      - ./data/grok-share-server/:/app/data/
  ## claude-mirror
  dddd-share-server:
    image: lyy0709/dddd-share-server:dev
    restart: always
    ports:
      - 8302:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      #PROXY_URL: "http://proxy:8080/proxy" # 代理服务地址,支持http和https，socks5，没有则留空默认走本地
      CHATPROXY: "https://chatproxy.com"
      # 内容审核及速率限制
      AUDIT_LIMIT_URL: "http://chatgpt-share-server-fox:6956/api/dddd/auditLimit"
      OAUTH_URL: "http://chatgpt-share-server-fox:6956/api/dddd/oauth"
      APIAUTH: Doraemon
    volumes:
      - ./claude_config.yaml:/app/config.yaml
      - ./data/dddd-share-server/:/app/data/
  chatgpt-share-server-fox:
    image: xiaomifengd/chatgpt-share-server-fox:latest
    restart: always
    ports:
      - "8400:6956"
    depends_on:
      - mysql
      - chatgpt-share-server
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cool?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: "" # 如果Redis没有设置密码，保持为空
      APIAUTH: Doraemon
    volumes:
      - ./data/chatgpt-share-server-fox/logs/:/tmp/logs
      - ./data/chatgpt-share-server-fox/imageData/:/data/upload
      - ./data/chatgpt-share-server-fox/file/:/data/file
